### ISSUE TITLE
Show idle resources as grey

### ISSUE THREAD

**Issue by JimTharioAmazon** [aws-solutions/media-services-application-mapper#102]
For resources with a RUNNING or IDLE state, show the node as grey when they are idle or disabled. MediaLive has a concept of IDLE. Ground appliances have idle/completed jobs. CloudFront has a deployed or disabled distribution.

**Comment by dthomasson** [comment]
This would be a welcome addition. Our workflow has up to 30 channels that have a mix of RUNNING and IDLE. For Ops teams that need to be first and fast responders, the gray would immediately isolate/hightlight those channels that are in fact active.

**Comment by Joaquin6** [comment]
@JimTharioAmazon From all MSAM supported node types, do we know which expose properties for running state and which dont?

**Comment by JimTharioAmazon** [comment]
**A complete list w/idle indicators**:
CloudFront: Status attribute (list and describe) (!Deployed)
EC2: look at describe_instance_status function (!Running)
MediaConnect: Status attribute from list_flows function (!Active)
MediaLive: State attribute (list and describe) (!Running)
MediaPackage: n/a
MediaStore: n/a
MediaTailor: n/a
S3: n/a
SPEKE: n/a
SSM Managed Instance: (hold until encoder status is merged)
User Defined Node: n/a

**Comment by JimTharioAmazon** [comment]
A few more design thoughts on this one.

Today, we have the inventory task (update nodes) running regularly in the cloud, which means the running status that comes with a list or describe call will get updated in the Content table for those resources automatically every few seconds or minutes.

I'd like to have this implemented as a mechanism where we periodically update the model/diagram data for specific resources or resource types (another timer) using a new extension of the existing REST API (if needed) to load cached resources.

The tool's bootstrap workflow and the "update" workflow share a certain amount of processing. The bootstrap process assumes nothing is there yet, and the update process assumes we are updating something already there and reacting to it.

Both bootstrap and update processes decide which render color to use based on the data received from the Content table.

**Comment by JimTharioAmazon** [comment]
Longer term, our polling will get replaced by event handlers when we implement #77 and as changes happen they'll get pushed via MQTT to the browser code.

**Comment by JimTharioAmazon** [comment]
We're going to hold on to this one until 1.7.0 so we can do a little more testing and tuning to the feature.
