### ISSUE TITLE
Provide mechanism to export current diagrams & tiles as single JSON and reimport later

### ISSUE THREAD

**Issue by 090media** [aws-solutions/media-services-application-mapper#152]
For certain live events we produce, we configure diagrams and tiles in MSAM for a large number of MediaLive channels (and their associated nodes. When the event is over, it would be nice to archive all of that work as a JSON and perhaps to be able to reimport it later, should we do a similar event with the same channels/nodes.

**Comment by tskamaldeep** [comment]
In addition to the mentioned request, please suggest if there is an easier way to configure live channels for events on a weekly basis. We may need to configure up to 60 events over the weekend and have the tiles/diagrams show up. Channels are not used again once the events are over. New channels implies new effort to configure the dashboard to be current and active. Please provide guidance on whether any kind of auto-discovery in MediaLive/MediaPackage is possible? Thanks for reviewing.

**Comment by JimTharioAmazon** [comment]
This might be a good situation to use the REST API directly to create diagrams and tiles in bulk. If you have some orchestration (or CloudFormation template) building the the channel resources, another program (Lambda) could use the ARNs from the channels resources to create a diagram and tile. The reverse could happen when the channel resources are deleted.

This document can help with that.

https://github.com/aws-solutions/aws-media-services-application-mapper/blob/main/docs/REST_API.md

**Comment by tskamaldeep** [comment]
Thank you for the document resource and guidance. Let me review this possibility.

**Comment by JimTharioAmazon** [comment]
Let us know if you need any recommendations on using the REST API for creating diagrams, tiles, or subscribing alarms to visual resources in diagrams.
