### ISSUE TITLE
Support AWS Resource Groups for diagram and tile creation

### ISSUE THREAD

**Issue by JimTharioAmazon** [aws-solutions/media-services-application-mapper#165]
This is a kind of extension to the use of tags for diagram and tile creation.

https://docs.aws.amazon.com/ARG/latest/userguide/welcome.html
https://console.aws.amazon.com/resource-groups/groups

`You can use resource groups to organize your AWS resources. Resource groups make it easier to manage and automate tasks on large numbers of resources at one time. `

**Comment by morjoan** [comment]
I believe implementing #176 automatically addresses this issue. From what I can tell though, there is still no support for media services in resource groups.
