### ISSUE TITLE
Change the colors of Tiles in alarm

### ISSUE THREAD

**Issue by Awot83** [aws-solutions/media-services-application-mapper#388]
Hello, 
(Maybe it's already possible, but i didn't find how) 

I'd like to change the colors of Tiles in alarms: now it is a red outline of the Tile, 
it would be nice to have a full red rectangle when the Tile is in alarm in order to be more visible
is it possible, and how ? 

thanks,

**Comment by raulmlamzn** [comment]
@Awot83 Thanks for the suggestion. No, only the nodes inside a Diagram are displayed with a full red rectangle when in alarm, and the Tiles are displayed with the red outline. We've carefully considered your feedback and have decided not to include this feature in a future release.
