### ISSUE TITLE
MSAM not installing correctly 

### ISSUE THREAD

**Issue by grf1** [aws-solutions/media-services-application-mapper#404]
**Describe the bug**
Initially installing this with the root CF template from the hosted docs failed with an S3 permissions error. Launching with the root template with this link: https://solutions-reference.s3.amazonaws.com/media-services-application-mapper/latest/aws-media-services-application-mapper-release.template did work - odd!

However, following the install the actual application itself doesn't seem to work as I'd expect, I've got media connect flows configured in the same region as MSAM but nothing shows in MSAM. The search function doesn't work, and overall it feels like something isn't quite right. I can't see any nodes that would form part of a tile, and I can't seem to make diagrams. The browser page hangs for ages on initial launch, and when I go to advance settings, then it finally loads. However all the refresh durations are by default set to NaN - again this doesn't seem right.

**Expected behavior**
Media connect flows would automatically appear in MSAM as nodes. 

**Desktop (please complete the following information):**
- OS: MacOS 13.4, tried Safari, Chrome, and Firefox

**Comment by raulmlamzn** [comment]
Thank you for your input. We will consider your feedback and have added this request to our backlog for this solution.
