### ISSUE TITLE
Migrate from API keys to IAM authentication for REST

### ISSUE THREAD

**Issue by JimTharioAmazon** [aws-solutions/media-services-application-mapper#50]
Internal user wants to have multiple access roles for browser connections.

Operator (change anything, diagrams, tiles, alarms, etc.)
Viewer (read only, no changes to back-end)

Process for adding new users changes (IAM users, or Cognito user pool)
Stored credentials on browser-side changes

Browser code needs to be aware of read-only role

**Comment by SteveWardAmazon** [comment]
It would be useful to be able to create MSAM-specific users with least-permission for the read-only functionality. Needed so external users could be granted limited access that could be easily disabled when no longer needed.

**Comment by JimTharioAmazon** [comment]
I think we'll need to consider Cognito integration versus a generic IAM integration. We have several users out there with existing authentication repositories in AWS cloud and elsewhere. Cognito can federate with repositories from Microsoft Active Directory Federation Services, Okta, Auth0, Ping Identity, Google, Facebook and others.
