### ISSUE TITLE
Provide link in alert view to relevant service log

### ISSUE THREAD

**Issue by SteveWardAmazon** [aws-solutions/media-services-application-mapper#63]
Would like alerts/alarms to include a link to the relevant log stream (when available).

**Comment by JimTharioAmazon** [comment]
We'll need to know the log stream name and date range of interest.

**Comment by JimTharioAmazon** [comment]
Similar to link to CloudWatch metrics that already exists.

**Comment by JimTharioAmazon** [comment]
Diagrams only for now.
